name: CI Setup

on:
  workflow_call:

jobs:
  common-setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: "true"
      - name: Checkout LFS objects
        run: git lfs checkout

      - uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Create k8s Kind Cluster
        run: bash ./scripts/konk-ci/01-kind.sh

      - name: Install Serving
        run: bash ./scripts/konk-ci/02-serving.sh

      - name: Install Kourier
        run: bash ./scripts/konk-ci/02-kourier.sh

      - name: Setup domain and autoscaler
        run: |
          INGRESS_HOST="127.0.0.1"
          KNATIVE_DOMAIN=$INGRESS_HOST.sslip.io
          kubectl patch configmap -n knative-serving config-domain -p "{\"data\": {\"$KNATIVE_DOMAIN\": \"\"}}"
          kubectl patch configmap -n knative-serving config-autoscaler -p "{\"data\": {\"allow-zero-initial-scale\": \"true\"}}"
          kubectl patch configmap -n knative-serving config-features -p "{\"data\": {\"kubernetes.podspec-affinity\": \"enabled\"}}"
          kubectl label node knative-control-plane loader-nodetype=worker
